### ISSUE TITLE
When trying to use in Programmatic API es7 errors

### ISSUE THREAD

**Issue by Nikamura** [facebook/mention-bot#100]
Just using provided example produces:

```****/node_modules/mention-bot/mention-bot.js:18
async function downloadFileAsync(url: string, cookies: ?string): Promise<string> {
      ^^^^^^^^

SyntaxError: Unexpected token function
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Module._extensions..js (module.js:416:10)
    at Object.require.extensions.(anonymous function) [as .js] (****/node_modules/babel-register/lib/node.js:134:7)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (****/node_modules/mention-bot/run-mention-bot.js:12:18)
    at Module._compile (module.js:409:26)```

**Comment by vjeux** [comment]
I'm sorry but I don't have the time to help you investigate what is going wrong :( I'm going to close down this issue, but feel free to keep posting here and others to help out.
