### ISSUE TITLE
SyntaxError: Unexpected token function

### ISSUE THREAD

**Issue by LinusU** [facebook/mention-bot#179]
When trying to require mention-bot as a module, I'm getting the following error:

```text
node_modules/mention-bot/mention-bot.js:18
async function downloadFileAsync(url: string, cookies: ?string): Promise<string> {
      ^^^^^^^^
SyntaxError: Unexpected token function
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Module._extensions..js (module.js:579:10)
    at Object.require.extensions.(anonymous function) [as .js] (node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (node_modules/mention-bot/run-mention-bot.js:12:18)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/linus/dooer/service-mention-bot/index.js:3:20)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```

My code is currently only one line:

```js
require('mention-bot')
```

I installed mention-bot with:

```sh
npm install --save mention-bot
```

**Comment by vjeux** [comment]
Arg, looks like the transpilation step is broken before we publish to npm. @gyandeeps do you know why that would be?

**Comment by mspangdal** [comment]
this effectively breaks the sample api usage,  is there a workaround for using the api?
