### ISSUE TITLE
Unexpected token ILLEGAL when running npm start (for the first time)

### ISSUE THREAD

**Issue by nkammah** [facebook/mention-bot#56]
after running npm install, running npm start produces : 

```
$ npm start

> mention-bot@0.0.1 start /var/nassim/mention-bot
> node run-server.js


/var/nassim/mention-bot/mention-bot.js:22
    args.push('-H', `Cookie: ${ cookies }`);
                    ^
SyntaxError: Unexpected token ILLEGAL
    at Module._compile (module.js:439:25)
    at loader (/var/nassim/mention-bot/node_modules/babel-core/node_modules/babel-register/lib/node.js:130:5)
    at Object.require.extensions.(anonymous function) [as .js] (/var/nassim/mention-bot/node_modules/babel-core/node_modules/babel-register/lib/node.js:140:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (server.js:14:18)
    at Module._compile (module.js:456:26)
    at loader (/var/nassim/mention-bot/node_modules/babel-core/node_modules/babel-register/lib/node.js:130:5)
```
node version : v0.10.16
Any help appreciated!

**Comment by vjeux** [comment]
I can reproduce on node v0.10.16, but if you upgrade to node 4, it works fine. My guess is that node now supports backtick natively so babel doesn't transform it anymore.

Few things that you can do:
- Upgrade to node 4
- Update the list of transforms to transform backticks so that it works on node 0.10

**Comment by Friss** [comment]
Should probably update `engines` config in the `package.json` for the newer versions of node. I ran into this same problem.

**Comment by vjeux** [comment]
@friss mind sending a pull request?
