### ISSUE TITLE
bunto-mention-bot is not working!

### ISSUE THREAD

**Issue by SuriyaaKudoIsc** [facebook/mention-bot#94]
Request for an answer for this issue to @vjeux!

----

I build a bot using mention-bot for the @Bunto organization. It's called @bunto-mention-bot.

The @bunto-mention-bot doesn't mention me as a potential reviewers on pull requests like this https://github.com/bunto/mention-bot/pull/3! I'm still not notified by this bot.

What should I do?

 - Source of the bunto-mention-bot: https://github.com/bunto/mention-bot

*Yours,*
[**Suriyaa Kudo**](https://github.com/SuriyaaKudoIsc) :octocat:

**Comment by Deborah-Digges** [comment]
I see that the pull request is for changes to a `.md` file. Could this be the reason that it is not triggering notifications to you? I also see that your [.metion-bot](https://github.com/bunto/mention-bot/blob/master/.mention-bot#L17) blacklists `.md` files

**Comment by SuriyaaKudoIsc** [comment]
@Deborah-Digges Still not working: https://github.com/bunto/mention-bot/pull/4!

**Comment by Deborah-Digges** [comment]
This is happening because the algorithm is returning an empty list of reviewers for this particular PR. You can try it using the API:


```
mentionBot.guessOwnersForPullRequest("https://github.com/bunto/mention-bot", 3, "SuriyaaKudoIsc", "master", {}, github)
.then(function(users) {   
    console.log(users);
})
.catch(function(err) {
console.error(err);
});
```

You will see an empty list. If the list is empty, [the code](https://github.com/facebook/mention-bot/blob/master/server.js#L165) skips this particular pull request.

To avoid this, set the configuration for 
```
{"alwaysNotifyForPaths": [
  {
       "name": "ghuser", // The user's Github username
       "files": ["*.*"] // The array of file globs associated with the user
    }
]}
```
in `.mention-bot` to avoid the list ever being empty

**Comment by SuriyaaKudoIsc** [comment]
Should I add this to the **`server.js`**?:

```bash
mentionBot.guessOwnersForPullRequest("https://github.com/bunto/mention-bot", 3, "SuriyaaKudoIsc", "master", {}, github)
.then(function(users) {   
    console.log(users);
})
.catch(function(err) {
console.error(err);
});
```

**Comment by Deborah-Digges** [comment]
No, this was something I ran in the node console just to see what's going on. Replace `ghuser` with the name of the default user for all pull requests.

**Comment by SuriyaaKudoIsc** [comment]
With my name as a maintainer of the project or the user names of the all contributors?

**Comment by SuriyaaKudoIsc** [comment]
@Deborah-Digges Add my name to it and it's still not working: https://github.com/bunto/mention-bot/pull/5 & https://github.com/bunto/mention-bot/pull/6!

**Comment by hunkim** [comment]
@SuriyaaKudoIsc Did you make any changes in the code? Did you try the local test?

```
1) npm test

2) 
curl -X POST -d @__tests__/data/23.webhook http://localhost:5000/
// Check if it has commented here: https://github.com/fbsamples/bot-testing/pull/23
```

I just run my own mention-bot, and it was successful.

**Comment by SuriyaaKudoIsc** [comment]
@hunkim I did some changes at https://github.com/bunto/mention-bot (commit history: https://github.com/bunto/mention-bot/commits/master).

----

I get this error output in my Windows 10 CMD:

```cmd
C:\Users\Suriyaa\Downloads\mention-bot>npm test

> mention-bot@0.0.1 test C:\Users\Suriyaa\Downloads\mention-bot
> flow && jest

events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: spawn C:\Users\Suriyaa\Downloads\mention-bot\node_modules\flow-bin\vendor\flow ENOENT
    at exports._errnoException (util.js:856:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:474:9)
    at process._tickCallback (node.js:388:17)
    at Function.Module.runMain (module.js:449:11)
    at startup (node.js:139:18)
    at node.js:999:3
npm ERR! Test failed.  See above for more details.

C:\Users\Suriyaa\Downloads\mention-bot>curl -X POST -d @__tests__/data/23.webhook http://localhost:5000/
curl: (7) Failed to connect to localhost port 5000: Connection refused

C:\Users\Suriyaa\Downloads\mention-bot>
```

**Comment by hunkim** [comment]
@SuriyaaKudoIsc Thanks for the information. You need to make sure your changes pass the local tests. Good luck!

**Comment by SuriyaaKudoIsc** [comment]
I think that *Windows is not supported* for the **`flow` npm dependency** because I get this error:

```cmd
C:\Users\Suriyaa\Downloads\mention-bot>npm test

> mention-bot@0.0.1 test C:\Users\Suriyaa\Downloads\mention-bot
> flow && jest

events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: spawn C:\Users\Suriyaa\Downloads\mention-bot\node_modules\flow-bin\vendor\flow ENOENT
    at exports._errnoException (util.js:856:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:474:9)
    at process._tickCallback (node.js:388:17)
    at Function.Module.runMain (module.js:449:11)
    at startup (node.js:139:18)
    at node.js:999:3
npm ERR! Test failed.  See above for more details.

C:\Users\Suriyaa\Downloads\mention-bot>
```

> Read https://github.com/facebook/flow/issues/1616 and https://github.com/facebook/flow/issues/6!

**Comment by hunkim** [comment]
@SuriyaaKudoIsc Can you test your mention-bot in Linux or AWS EC2? I really think you should be able to run tests after modifying source code.

**Comment by SuriyaaKudoIsc** [comment]
I already published bunto-mention-bot on Heroku (Linux Container).

**Comment by SuriyaaKudoIsc** [comment]
But it doesn't worked.

**Comment by vjeux** [comment]
I'm sorry but I don't have the time to help you investigate what is going wrong :( I'm going to close down this issue, but feel free to keep posting here and others to help out.

**Comment by SuriyaaKudoIsc** [comment]
:+1: Ok.
